@client.command()
async def message(ctx):
    embedVar = discord.Embed(title="🚀 BIENVENUE SUR NOTRE DISCORD", description="\u200B", color=0xcf00ff)
    embedVar.set_thumbnail(url="https://cdn.discordapp.com/avatars/953040690701553715/2db7d5e5789f7586632ad4a762de345e.webp?size=128")
    embedVar.add_field(name="ToTheMoon est la pour vous servir !", value="\u200B", inline=False)
    embedVar.add_field(name="Nous avons beaucoup travailler pour vous présenter ce bot\nOn espère qu'il va vout plaire !\n Voici la liste de toutes les commandes !", value="\u200B", inline=False)
    embedVar.add_field(name="\u200B", value="🌕🌙 **MOON**\n\n**Liste des cryptos :**\n!coin\n\n**Liste des monnaies :**\n!money\n\n**Pour connaître le cours d'une monnaie :**\n!getPrice <crypto> <monnaie>\n\n", inline=True)
    embedVar.add_field(name="\u200B", value="🦊 **FOXY**\n\n**Les infos du serveur :**\n!serverinfo\n\n**Pour faire un quiz :**\n!quiz\n\n**Pour une surprise :**\n!coucou\n\n", inline=True)
    embedVar.add_field(name="\u200B", value="👾 **AUTRES**\n\n**La boule magique :**\n!8ball <Votre question ?>\n\n**Voir son avatar :**\n!avatar @nom_utilisateur\n\n**Pour acheter de la drogue :**\n!dealer\n\n", inline=True)
    embedVar.add_field(name="\u200B", value="\u200B", inline=False)
    embedVar.add_field(name="\u200B", value="Voici notre github pour voir et suivre notre projet, c'est open source : https://github.com/schwiG5/API_SERVICE_WEB")
    embedVar.add_field(name="\u200B", value="Vous allez donc pouvoir experimenter toutes les commandes dans la catégorie zoo", inline=False)
    embedVar.add_field(name="\u200B", value="Dans la catégorie **CRYPTOMONNAIES** vous pourrez voir le cours de toutes les cryptos actualisés toutes les heures !", inline=False)
    embedVar.add_field(name="\u200B", value="Mettez nous 20/20 aussi merci <3", inline=False)
    embedVar.set_footer(text="© Les bras cassés | ESILV")
    embedVar.add_field(name="\u200B", value="\u200B", inline=False)
    await ctx.send(embed=embedVar)